# Site Settings
title: "Observations from the Little Bunker"
tagline: "Methodically tracking our changing world"
description: "A systematic observation of climate change, extreme weather events, and their cascading effects on society"
baseurl: ""
url: "https://littlebunker.com"
timezone: UTC

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
collections:
  events:
    output: true
    permalink: /events/:path/
  observations:
    output: true
    permalink: /observations/:path/
  topics:
    output: true
    permalink: /topics/:path/

# Default front matter - FIXED ORDER!
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: "calm@littlebunker.com"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      is_feed: false
  - scope:
      path: "_posts"
      type: "posts"
    values:
      is_feed: true
      layout: "feed_item"    # ← This will apply to RSS posts with is_feed: true


# ActivityPub Configuration
activitypub:
  username: "calm"
  domain: "littlebunker.com"
  display_name: "The Observer"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Feed settings
feed:
  categories:
    - climate-science
    - extreme-weather
    - disasters
    - social-impact

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
