# Site Settings
title: "Observations from the Little Bunker"
tagline: "Methodically tracking our changing world"
description: "A systematic observation of climate change, extreme weather events, and their cascading effects on society"
baseurl: ""
url: "https://littlebunker.com"
timezone: UTC

# Theme
theme: minima

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
collections:
  events:
    output: true
    permalink: /events/:path/
  observations:
    output: true
    permalink: /observations/:path/
  topics:
    output: true
    permalink: /topics/:path/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      author: "calm@littlebunker.com"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination
paginate: 24
paginate_path: "/page/:num/"

# Feed settings
feed:
  categories:
    - climate-science
    - extreme-weather
    - disasters
    - social-impact

# Exclude files
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
